### ISSUE TITLE
Doesn't work out of the box

### ISSUE THREAD

**Issue by omrikiei** [windmilleng/servantes#97]
When trying to bootstrap the project with tilt I get the following:
```
Beginning Tiltfile execution
Traceback (most recent call last):
  /Users/omrikiie/projects/servantes/Tiltfile:2: in <toplevel>
Error: Unknown feature flag: snapshots
```

**Comment by jazzdan** [comment]
Hi @omrikiei, what version of Tilt were you using? Can you try upgrading to the most recent version, v0.10.4?

**Comment by omrikiei** [comment]
Tried, worked, thanks!
